# Generated by Django 3.2 on 2024-07-05 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20240705_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('id',), 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('id',), 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
    ]
